//! Shared API types for pairing sessions.
//!
//! These types define the HTTP request/response shapes used by both the
//! registry server and the LAN pairing server. Keeping them in `auths-core`
//! ensures a single source of truth.

use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use auths_verifier::types::DeviceDID;

/// A base64url-encoded (no padding) byte string.
///
/// Wraps a `String` that is expected to contain valid base64url-encoded data.
/// Use [`encode`](Self::encode) to create from raw bytes and
/// [`decode`](Self::decode) to recover the original bytes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(transparent)]
pub struct Base64UrlEncoded(String);

impl Base64UrlEncoded {
    /// Wrap a raw base64url-encoded string (no validation).
    pub fn from_raw(s: String) -> Self {
        Self(s)
    }

    /// Encode raw bytes to base64url (no padding).
    pub fn encode(bytes: &[u8]) -> Self {
        Self(URL_SAFE_NO_PAD.encode(bytes))
    }

    /// Decode the contained base64url string back to bytes.
    pub fn decode(&self) -> Result<Vec<u8>, base64::DecodeError> {
        URL_SAFE_NO_PAD.decode(&self.0)
    }

    /// View the raw base64url string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::ops::Deref for Base64UrlEncoded {
    type Target = str;
    fn deref(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for Base64UrlEncoded {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Session status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum SessionStatus {
    /// Waiting for responding device.
    Pending,
    /// Response received, ready for initiator to retrieve.
    Responded,
    /// Completed (both parties confirmed).
    Completed,
    /// Cancelled by either party.
    Cancelled,
    /// Expired.
    Expired,
}

/// Request to create a new pairing session.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct CreateSessionRequest {
    /// Session ID (generated by initiator).
    pub session_id: String,
    /// Controller DID of the initiator.
    pub controller_did: String,
    /// Initiator's ephemeral X25519 public key (base64url encoded).
    pub ephemeral_pubkey: Base64UrlEncoded,
    /// 6-char alphanumeric short code.
    pub short_code: String,
    /// Capabilities to grant to the paired device.
    #[serde(default)]
    pub capabilities: Vec<String>,
    /// Expiry timestamp (Unix seconds).
    pub expires_at: i64,
}

/// Response to session creation.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct CreateSessionResponse {
    /// Session ID.
    pub session_id: String,
    /// Status.
    pub status: SessionStatus,
    /// Short code for manual entry.
    pub short_code: String,
    /// Full URI for QR code.
    pub uri: String,
    /// Time remaining in seconds.
    pub ttl_seconds: u64,
}

/// Request to submit a pairing response.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct SubmitResponseRequest {
    /// Responder's X25519 ephemeral public key (base64url encoded).
    pub device_x25519_pubkey: Base64UrlEncoded,
    /// Responder's Ed25519 signing public key (base64url encoded).
    pub device_signing_pubkey: Base64UrlEncoded,
    /// Responder's DID (did:key:z6Mk...).
    #[schemars(with = "String")]
    pub device_did: DeviceDID,
    /// Ed25519 signature over binding message (base64url encoded).
    pub signature: Base64UrlEncoded,
    /// Optional device name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_name: Option<String>,
}

/// Response when getting session status.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct GetSessionResponse {
    /// Session ID.
    pub session_id: String,
    /// Current status.
    pub status: SessionStatus,
    /// Time remaining in seconds (0 if expired).
    pub ttl_seconds: u64,
    /// The pairing token (for responding device).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<CreateSessionRequest>,
    /// The response (for initiating device, once submitted).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response: Option<SubmitResponseRequest>,
}

/// Response for successful operations.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct SuccessResponse {
    /// Whether the pairing operation succeeded.
    pub success: bool,
    /// Human-readable status message.
    pub message: String,
}
