#!/usr/bin/env python3
"""Regenerate canonical input fixtures + frozen golden outputs FROM keripy 1.3.4.

Writes two trees plus a provenance manifest:
  - fixtures/*.json : the deterministic INPUTS both keripy and the auths CLI
                      consume (KELs, ksn records, ACDC).
  - vectors/*.json  : the frozen EXPECTED OUTPUTS computed by the keripy oracle
                      (ksn state, did:webs docs, oobi replies, ipex exn). These
                      are the drift/provenance anchors: test_vectors_provenance.py
                      asserts re-running this script reproduces them byte-for-byte.
  - MANIFEST.yaml   : per-file {path, surface, source: keripy, version,
                      gen_command, sha256} (mirrors interop/vectors/MANIFEST.yaml).

Every value is deterministic (fixed key material, explicit timestamps), so the
checked-in files and their sha256s are stable across regenerations. The expected
outputs are produced ONLY by keripy oracle code in oracle.py — never copied from
auths output.

Run:  python3 gen_vectors.py
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import oracle as o

HERE = Path(__file__).resolve().parent
FIX = HERE / "fixtures"
VEC = HERE / "vectors"
KERI_VERSION = __import__("keri").__version__


def _canon_bytes(obj) -> bytes:
    """Canonical JSON bytes: sorted keys, compact separators, trailing newline."""
    return (
        json.dumps(obj, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode()


def main() -> None:
    FIX.mkdir(parents=True, exist_ok=True)
    VEC.mkdir(parents=True, exist_ok=True)
    entries: list[dict] = []

    def emit(tree: Path, rel: str, obj, surface: str, gen: str) -> None:
        path = tree / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        data = _canon_bytes(obj)
        path.write_bytes(data)
        entries.append(
            {
                "path": f"{tree.name}/{rel}",
                "surface": surface,
                "source": "keripy",
                "version": KERI_VERSION,
                "gen_command": gen,
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        )

    # ── Inception fixtures (shared inputs) ──────────────────────────────────
    icp = o.icp_ed()
    icp2 = o.icp_ed2()
    icp_p = o.icp_p256()
    sender, recipient = icp.pre, icp2.pre

    emit(FIX, "kel-ed25519.json", o.kel_json(icp), "ksn/did-webs/oobi",
         "eventing.incept(keys=[Verfer(bytes(0..32)).qb64], code=Blake3_256)")
    emit(FIX, "kel-p256.json", o.kel_json(icp_p), "did-webs",
         "eventing.incept(keys=[P256 Verfer(scalar=int(bytes(1..33))).qb64], code=Blake3_256)")
    emit(FIX, "ksn-ingest.json", o.ksn_ingest_input(icp), "ksn-ingest",
         "eventing.state(...).asdict()  # keripy-published ksn wire record")
    emit(FIX, "acdc.json", o.ipex_acdc(sender, recipient), "ipex",
         "proving.credential(schema, issuer, data={dt}, recipient, status=registry)")

    # ── Golden outputs (keripy oracle) ──────────────────────────────────────
    emit(VEC, "ksn-emit.json", o.ksn_state(icp), "ksn-emit",
         "eventing.state(pre,sn=0,pig='',dig,fn=0,eilk='icp',keys,eevt,sith='1',"
         "ndigs=[],toad=0,wits=[],cnfg=[],stamp=epoch)._asdict()")
    emit(VEC, "ksn-ingest-resolved.json", o.ksn_ingest_expected(icp), "ksn-ingest",
         "subset {i,k,s} of eventing.state(...)._asdict()")
    emit(VEC, "did-webs-ed25519.json",
         o.did_webs(icp, o.ed_verfer(), "example.com"), "did-webs",
         "gen_did_document(Ed25519→OKP x-only JWK)")
    emit(VEC, "did-webs-p256.json",
         o.did_webs(icp_p, o.p256_verfer(), "example.com"), "did-webs",
         "gen_did_document(P-256→EC x/y JWK)")
    emit(VEC, "oobi-loc-scheme.json",
         o.oobi_loc_scheme(icp, "http://127.0.0.1:5642/"), "oobi",
         "eventing.reply(route='/loc/scheme', data={eid,scheme,url}, stamp=epoch)")
    emit(VEC, "oobi-end-role.json", o.oobi_end_role(icp), "oobi",
         "eventing.reply(route='/end/role/add', data={cid,role,eid}, stamp=epoch)")
    emit(VEC, "ipex-grant.json", o.ipex_grant(sender, recipient), "ipex",
         "exchanging.exchange(route='/ipex/grant', payload={m:'',i:recp}, "
         "sender, embeds={acdc}, date=dt)")
    emit(VEC, "ipex-admit.json", o.ipex_admit(sender, recipient), "ipex",
         "exchanging.exchange(route='/ipex/admit', payload={m:''}, sender=recp, "
         "dig=grant.said, date=dt)")

    # ── MANIFEST ────────────────────────────────────────────────────────────
    import yaml

    header = (
        "# MANIFEST.yaml — provenance for every conformance fixture + vector.\n"
        "# GENERATED by gen_vectors.py from keripy (the oracle). Do not hand-edit;\n"
        "# re-run `python3 gen_vectors.py` and review the diff. keripy-version\n"
        "# drift changes the sha256s and fails test_vectors_provenance.py.\n"
        "#\n"
        "# Per-entry: {path, surface, source: keripy, version, gen_command, sha256}\n\n"
    )
    (HERE / "MANIFEST.yaml").write_text(
        header + yaml.safe_dump({"vectors": entries}, sort_keys=False, width=10_000)
    )

    print(f"wrote {len(entries)} files from keripy {KERI_VERSION}")
    for e in entries:
        print(f"  {e['path']:<32} {e['sha256'][:12]}…")


if __name__ == "__main__":
    main()
