//! Error-code lint: locks the error corpus's house style so drift fails the build.
//!
//! Three invariants, checked against `docs/errors/registry.lock` (generated by
//! `gen-error-docs`) and the per-code docs:
//!
//! 1. Every `[AUTHS-E####]` string literal emitted in `crates/**/src` names a
//!    registered code — a code that resolves to "unknown" via `auths error show`
//!    is a broken promise.
//! 2. Every registered code's generated doc carries a `## Suggestion`, except an
//!    explicit allowlist of codes whose message intentionally carries its own
//!    guidance. Coverage only climbs.
//! 3. The user-facing render surface never reaches for `panic!`/`todo!` or a
//!    `Box<dyn Error>` — a failure to render an error must not itself panic.

use std::collections::BTreeSet;
use std::path::Path;

use walkdir::WalkDir;

/// Codes whose generated doc intentionally has no `## Suggestion` — the variant's
/// own message carries the guidance, so a generic fix line would only dilute it.
/// Keep this list tight: adding a code here is a deliberate, reviewable choice.
const SUGGESTIONLESS_ALLOWLIST: &[&str] = &[
    // auths-sdk SetupError::InvalidSetupConfig — the message states the exact param.
    "AUTHS-E5007",
];

/// Ceiling on non-allowlisted codes that still lack a `## Suggestion` — the legacy
/// backlog that predates suggestion coverage. This is a one-way ratchet: coverage
/// may only climb (this number may only fall). It fails the build the moment a code
/// loses its suggestion or a new suggestion-less code lands, which is exactly the
/// silent-regression class the corpus is meant to lock out. Lower it as the backlog
/// is worked down; never raise it.
const MAX_UNDOCUMENTED_CODES: usize = 60;

/// Run the error-code lint against the workspace.
///
/// Args:
/// * `root`: the repository root.
///
/// Usage:
/// ```ignore
/// check_error_codes::run(workspace_root)?;
/// ```
pub fn run(root: &Path) -> anyhow::Result<()> {
    let registered = parse_registry_lock(root)?;
    if registered.is_empty() {
        anyhow::bail!(
            "docs/errors/registry.lock has no codes — run `cargo xtask gen-error-docs` first"
        );
    }

    let mut failures: Vec<String> = Vec::new();

    for (file, code) in scan_emitted_code_literals(root)? {
        if !registered.contains(&code) {
            failures.push(format!(
                "{file}: emits {code} but it is not in docs/errors/registry.lock \
                 (register it via an AuthsErrorInfo variant, or drop the tag)"
            ));
        }
    }

    let mut undocumented: Vec<String> = Vec::new();
    for code in &registered {
        if SUGGESTIONLESS_ALLOWLIST.contains(&code.as_str()) {
            continue;
        }
        if !doc_has_suggestion(root, code)? {
            undocumented.push(code.clone());
        }
    }
    if undocumented.len() > MAX_UNDOCUMENTED_CODES {
        failures.push(format!(
            "{} codes lack a `## Suggestion` but the ratchet allows at most {} — \
             coverage regressed. Add a suggestion to the offending AuthsErrorInfo arm \
             (do not raise the ceiling). Undocumented:\n{}",
            undocumented.len(),
            MAX_UNDOCUMENTED_CODES,
            indent(&undocumented)
        ));
    }

    failures.extend(scan_render_path_for_panics(root)?);

    if failures.is_empty() {
        println!(
            "  ok       {} error codes registered; all emitted tags lookupable, \
             suggestion coverage within ratchet ({} undocumented, ceiling {})",
            registered.len(),
            undocumented.len(),
            MAX_UNDOCUMENTED_CODES
        );
        Ok(())
    } else {
        anyhow::bail!("error-code lint failed:\n{}", indent(&failures));
    }
}

fn indent(items: &[String]) -> String {
    items
        .iter()
        .map(|f| format!("  - {f}"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Parse the registered codes from `docs/errors/registry.lock`.
fn parse_registry_lock(root: &Path) -> anyhow::Result<BTreeSet<String>> {
    let path = root.join("docs/errors/registry.lock");
    let text = std::fs::read_to_string(&path)
        .map_err(|e| anyhow::anyhow!("cannot read {}: {e}", path.display()))?;
    let mut codes = BTreeSet::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((code, _binding)) = line.split_once('=') {
            codes.insert(code.trim().to_string());
        }
    }
    Ok(codes)
}

/// Find every `[AUTHS-E####]` literal emitted in `crates/**/src`, paired with the
/// file it lives in. xtask is excluded — its own fixtures deliberately emit codes.
fn scan_emitted_code_literals(root: &Path) -> anyhow::Result<Vec<(String, String)>> {
    let crates_dir = root.join("crates");
    let mut hits = Vec::new();
    for entry in WalkDir::new(&crates_dir).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let path_str = path.to_string_lossy();
        if path_str.contains("/xtask/") || !path_str.contains("/src/") {
            continue;
        }
        let content = std::fs::read_to_string(path).unwrap_or_default();
        for code in extract_bracket_codes(&content) {
            hits.push((rel(root, path), code));
        }
    }
    Ok(hits)
}

/// Extract every `[AUTHS-E####]` code from `content` (the bracketed emission form).
fn extract_bracket_codes(content: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = content.as_bytes();
    let needle = b"[AUTHS-E";
    let mut i = 0;
    while let Some(pos) = find_from(bytes, needle, i) {
        let digits_start = pos + needle.len();
        let mut j = digits_start;
        while j < bytes.len() && bytes[j].is_ascii_digit() {
            j += 1;
        }
        // Exactly `[AUTHS-E<digits>]` with at least one digit.
        if j > digits_start && j < bytes.len() && bytes[j] == b']' {
            out.push(format!("AUTHS-E{}", &content[digits_start..j]));
        }
        i = pos + needle.len();
    }
    out
}

fn find_from(haystack: &[u8], needle: &[u8], from: usize) -> Option<usize> {
    if from >= haystack.len() {
        return None;
    }
    haystack[from..]
        .windows(needle.len())
        .position(|w| w == needle)
        .map(|p| p + from)
}

/// Whether the generated doc for `code` carries a `## Suggestion` section.
fn doc_has_suggestion(root: &Path, code: &str) -> anyhow::Result<bool> {
    let path = root.join("docs/errors").join(format!("{code}.md"));
    match std::fs::read_to_string(&path) {
        Ok(text) => Ok(text.contains("## Suggestion")),
        // A missing doc is a staleness issue gen-error-docs owns; report as "no
        // suggestion" so it surfaces here too rather than passing silently.
        Err(_) => Ok(false),
    }
}

/// Scan the error render surface for constructs that could panic while rendering
/// a user-facing error. Keeps the guard narrow (the renderer file) to avoid
/// false positives elsewhere.
fn scan_render_path_for_panics(root: &Path) -> anyhow::Result<Vec<String>> {
    let renderer = root.join("crates/auths-cli/src/errors/renderer.rs");
    let mut failures = Vec::new();
    let Ok(content) = std::fs::read_to_string(&renderer) else {
        return Ok(failures);
    };
    let banned = [
        "panic!(",
        "todo!(",
        "unimplemented!(",
        "Box<dyn std::error::Error",
        "Box<dyn Error",
    ];
    for (n, line) in content.lines().enumerate() {
        let code = line.split("//").next().unwrap_or(line);
        if code.trim_start().starts_with("//") {
            continue;
        }
        for pat in banned {
            if code.contains(pat) {
                failures.push(format!(
                    "crates/auths-cli/src/errors/renderer.rs:{}: `{pat}` on the render surface",
                    n + 1
                ));
            }
        }
    }
    Ok(failures)
}

fn rel(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_bracketed_codes_only() {
        let src = r#"
            bail!("bad -O\n  [AUTHS-E0031]");
            let code = "AUTHS-E5909"; // bare, not bracketed
            eprintln!("[{code}]"); // dynamic, not a literal
            // reference to [AUTHS-E4203] in a comment
        "#;
        let codes = extract_bracket_codes(src);
        assert!(codes.contains(&"AUTHS-E0031".to_string()));
        assert!(codes.contains(&"AUTHS-E4203".to_string()));
        assert!(
            !codes.contains(&"AUTHS-E5909".to_string()),
            "a bare (non-bracketed) code is not an emission"
        );
    }

    #[test]
    fn unregistered_literal_is_detected() {
        // A bracket literal whose code is absent from the registry must be caught —
        // this is exactly the orphan-tag class the lint exists to lock out.
        let registered: BTreeSet<String> = ["AUTHS-E4203".to_string()].into_iter().collect();
        let emitted = extract_bracket_codes("guard: [AUTHS-E9999]");
        let unregistered: Vec<_> = emitted
            .iter()
            .filter(|c| !registered.contains(*c))
            .collect();
        assert_eq!(unregistered, vec![&"AUTHS-E9999".to_string()]);
    }

    #[test]
    fn ignores_partial_or_malformed_tags() {
        assert!(extract_bracket_codes("[AUTHS-E]").is_empty());
        assert!(extract_bracket_codes("[AUTHS-Eabcd]").is_empty());
        assert!(extract_bracket_codes("[AUTHS-E1234").is_empty());
    }
}
