/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NapiPairingHandle {
  static createSession(repoPath: string, capabilitiesJson?: string | undefined | null, timeoutSecs?: number | undefined | null, bindAddress?: string | undefined | null, enableMdns?: boolean | undefined | null, passphrase?: string | undefined | null): Promise<NapiPairingHandle>
  get session(): NapiPairingSession
  waitForResponse(timeoutSecs?: number | undefined | null): Promise<NapiPairingResponse>
  complete(deviceDid: string, devicePublicKeyHex: string, repoPath: string, capabilitiesJson?: string | undefined | null, passphrase?: string | undefined | null): Promise<NapiPairingResult>
  stop(): Promise<void>
}

export declare function addOrgMember(orgDid: string, memberDid: string, role: string, repoPath: string, capabilitiesJson?: string | undefined | null, passphrase?: string | undefined | null, note?: string | undefined | null, memberPublicKeyHex?: string | undefined | null): NapiOrgMember

export declare function addWitness(urlStr: string, repoPath: string, label?: string | undefined | null): NapiWitnessResult

export declare function compilePolicy(policyJson: string): string

export declare function createAgentIdentity(agentName: string, capabilities: Array<string>, repoPath: string, passphrase?: string | undefined | null): NapiAgentIdentityBundle

export declare function createIdentity(keyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiIdentityResult

export declare function createOrg(label: string, repoPath: string, passphrase?: string | undefined | null): NapiOrgResult

export declare function delegateAgent(agentName: string, capabilities: Array<string>, parentRepoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null, identityDid?: string | undefined | null): NapiDelegatedAgentBundle

export declare function evaluatePolicy(policyJson: string, issuer: string, subject: string, capabilities?: Array<string> | undefined | null, role?: string | undefined | null, revoked?: boolean | undefined | null, expiresAt?: string | undefined | null, repo?: string | undefined | null, environment?: string | undefined | null, signerType?: string | undefined | null, delegatedBy?: string | undefined | null, chainDepth?: number | undefined | null): NapiPolicyDecision

export declare function extendDeviceAuthorization(deviceDid: string, identityKeyAlias: string, expiresIn: number, repoPath: string, passphrase?: string | undefined | null): NapiExtensionResult

export declare function generateAuditReport(targetRepoPath: string, authsRepoPath: string, since?: string | undefined | null, until?: string | undefined | null, author?: string | undefined | null, limit?: number | undefined | null): string

export declare function getIdentityPublicKey(identityDid: string, repoPath: string, passphrase?: string | undefined | null): string

export declare function getLatestAttestation(repoPath: string, deviceDid: string): NapiAttestation | null

export declare function getPinnedIdentity(did: string, repoPath: string): NapiPinnedIdentity | null

export declare function joinPairingSession(shortCode: string, endpoint: string, token: string, repoPath: string, deviceName?: string | undefined | null, passphrase?: string | undefined | null): Promise<NapiPairingResponse>

export declare function linkDeviceToIdentity(identityKeyAlias: string, capabilities: Array<string>, repoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null): NapiLinkResult

export declare function listAttestations(repoPath: string): Array<NapiAttestation>

export declare function listAttestationsByDevice(repoPath: string, deviceDid: string): Array<NapiAttestation>

export declare function listOrgMembers(orgDid: string, includeRevoked: boolean, repoPath: string): string

export declare function listPinnedIdentities(repoPath: string): string

export declare function listWitnesses(repoPath: string): string

export interface NapiActionEnvelope {
  envelopeJson: string
  signatureHex: string
  signerDid: string
}

export interface NapiAgentIdentityBundle {
  agentDid: string
  keyAlias: string
  attestationJson: string
  publicKeyHex: string
  repoPath?: string
}

export interface NapiArtifactResult {
  attestationJson: string
  rid: string
  digest: string
  fileSize: number
}

export interface NapiAttestation {
  rid: string
  issuer: string
  subject: string
  deviceDid: string
  capabilities: Array<string>
  signerType?: string
  expiresAt?: string
  revokedAt?: string
  createdAt?: string
  delegatedBy?: string
  json: string
}

export interface NapiChainLink {
  issuer: string
  subject: string
  valid: boolean
  error?: string
}

export interface NapiCommitSignPemResult {
  signaturePem: string
  method: string
  namespace: string
}

export interface NapiCommitSignResult {
  signature: string
  signerDid: string
}

export interface NapiDelegatedAgentBundle {
  agentDid: string
  keyAlias: string
  attestationJson: string
  publicKeyHex: string
  repoPath?: string
}

export interface NapiExtensionResult {
  deviceDid: string
  newExpiresAt: string
  previousExpiresAt?: string
}

export interface NapiIdentityResult {
  did: string
  keyAlias: string
  publicKeyHex: string
}

export interface NapiLinkResult {
  deviceDid: string
  attestationId: string
}

export interface NapiOrgMember {
  memberDid: string
  role: string
  capabilitiesJson: string
  issuerDid: string
  attestationRid: string
  revoked: boolean
  expiresAt?: string
}

export interface NapiOrgResult {
  orgPrefix: string
  orgDid: string
  label: string
  repoPath: string
}

export interface NapiPairingResponse {
  deviceDid: string
  deviceName?: string
  devicePublicKeyHex: string
}

export interface NapiPairingResult {
  deviceDid: string
  deviceName?: string
  attestationRid: string
}

export interface NapiPairingSession {
  sessionId: string
  shortCode: string
  endpoint: string
  token: string
  controllerDid: string
}

export interface NapiPinnedIdentity {
  did: string
  label?: string
  trustLevel: string
  firstSeen: string
  kelSequence?: number
  pinnedAt: string
}

export interface NapiPolicyDecision {
  outcome: string
  reason: string
  message: string
}

export interface NapiRotationResult {
  controllerDid: string
  newKeyFingerprint: string
  previousKeyFingerprint: string
  sequence: number
}

export interface NapiVerificationReport {
  status: NapiVerificationStatus
  chain: Array<NapiChainLink>
  warnings: Array<string>
}

export interface NapiVerificationResult {
  valid: boolean
  error?: string
  errorCode?: string
}

export interface NapiVerificationStatus {
  statusType: string
  at?: string
  step?: number
  missingLink?: string
  required?: number
  verified?: number
}

export interface NapiWitnessResult {
  url: string
  did?: string
  label?: string
}

export declare function pinIdentity(did: string, repoPath: string, label?: string | undefined | null, trustLevel?: string | undefined | null): NapiPinnedIdentity

export declare function removePinnedIdentity(did: string, repoPath: string): void

export declare function removeWitness(urlStr: string, repoPath: string): void

export declare function revokeDeviceFromIdentity(deviceDid: string, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, note?: string | undefined | null): void

export declare function revokeOrgMember(orgDid: string, memberDid: string, repoPath: string, passphrase?: string | undefined | null, note?: string | undefined | null, memberPublicKeyHex?: string | undefined | null): NapiOrgMember

export declare function rotateIdentityKeys(repoPath: string, identityKeyAlias?: string | undefined | null, nextKeyAlias?: string | undefined | null, passphrase?: string | undefined | null): NapiRotationResult

export declare function runDiagnostics(repoPath: string, passphrase?: string | undefined | null): string

export declare function signActionAsAgent(actionType: string, payloadJson: string, keyAlias: string, agentDid: string, repoPath: string, passphrase?: string | undefined | null): NapiActionEnvelope

export declare function signActionAsIdentity(actionType: string, payloadJson: string, identityDid: string, repoPath: string, passphrase?: string | undefined | null): NapiActionEnvelope

/**
 * Sign an action envelope with a hex-encoded Ed25519 private key.
 *
 * Args:
 * * `private_key_hex`: Ed25519 seed as hex string (64 chars = 32 bytes).
 * * `action_type`: Application-defined action type (e.g. "tool_call").
 * * `payload_json`: JSON string for the payload field.
 * * `identity_did`: Signer's identity DID (e.g. "did:keri:E...").
 *
 * Usage:
 * ```ignore
 * let envelope = sign_action_raw("deadbeef...".into(), "tool_call".into(), "{}".into(), "did:keri:E...".into())?;
 * ```
 */
export declare function signActionRaw(privateKeyHex: string, actionType: string, payloadJson: string, identityDid: string): string

export declare function signArtifact(filePath: string, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null, note?: string | undefined | null, commitSha?: string | undefined | null): NapiArtifactResult

export declare function signArtifactBytes(data: Buffer, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null, note?: string | undefined | null, commitSha?: string | undefined | null): NapiArtifactResult

/**
 * Sign raw bytes with a raw Ed25519 private key, producing a dual-signed attestation.
 *
 * No keychain or filesystem access required.
 *
 * Args:
 * * `data`: The raw bytes to sign.
 * * `private_key_hex`: Ed25519 seed as hex string (64 chars = 32 bytes).
 * * `identity_did`: Identity DID string (must be `did:keri:` format).
 * * `expires_in`: Optional duration in seconds until expiration.
 * * `note`: Optional human-readable note.
 *
 * Usage:
 * ```ignore
 * let result = sign_artifact_bytes_raw(buffer, "abcd...".into(), "did:keri:E...".into(), None, None)?;
 * ```
 */
export declare function signArtifactBytesRaw(data: Buffer, privateKeyHex: string, identityDid: string, expiresIn?: number | undefined | null, note?: string | undefined | null, commitSha?: string | undefined | null): NapiArtifactResult

export declare function signAsAgent(message: Buffer, keyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignResult

export declare function signAsIdentity(message: Buffer, identityDid: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignResult

/**
 * Sign raw bytes with a hex-encoded Ed25519 private key.
 *
 * Args:
 * * `private_key_hex`: Ed25519 seed as hex string (64 chars = 32 bytes).
 * * `message`: The bytes to sign.
 *
 * Usage:
 * ```ignore
 * let sig = sign_bytes_raw("deadbeef...".into(), buffer)?;
 * ```
 */
export declare function signBytesRaw(privateKeyHex: string, message: Buffer): string

export declare function signCommit(data: Buffer, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignPemResult

/**
 * Verify an action envelope's Ed25519 signature with a raw public key.
 *
 * Args:
 * * `envelope_json`: The complete action envelope as a JSON string.
 * * `public_key_hex`: The signer's Ed25519 public key in hex format (64 chars).
 *
 * Usage:
 * ```ignore
 * let result = verify_action_envelope("{...}".into(), "abcd1234...".into())?;
 * ```
 */
export declare function verifyActionEnvelope(envelopeJson: string, publicKeyHex: string): NapiVerificationResult

export declare function verifyAttestation(attestationJson: string, issuerPkHex: string): Promise<NapiVerificationResult>

export declare function verifyAttestationWithCapability(attestationJson: string, issuerPkHex: string, requiredCapability: string): Promise<NapiVerificationResult>

export declare function verifyAtTime(attestationJson: string, issuerPkHex: string, atRfc3339: string): Promise<NapiVerificationResult>

export declare function verifyAtTimeWithCapability(attestationJson: string, issuerPkHex: string, atRfc3339: string, requiredCapability: string): Promise<NapiVerificationResult>

export declare function verifyChain(attestationsJson: Array<string>, rootPkHex: string): Promise<NapiVerificationReport>

export declare function verifyChainWithCapability(attestationsJson: Array<string>, rootPkHex: string, requiredCapability: string): Promise<NapiVerificationReport>

export declare function verifyChainWithWitnesses(attestationsJson: Array<string>, rootPkHex: string, receiptsJson: Array<string>, witnessKeysJson: Array<string>, threshold: number): Promise<NapiVerificationReport>

export declare function verifyDeviceAuthorization(identityDid: string, deviceDid: string, attestationsJson: Array<string>, identityPkHex: string): Promise<NapiVerificationReport>

export declare function version(): string
