/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function addOrgMember(orgDid: string, memberDid: string, role: string, repoPath: string, capabilitiesJson?: string | undefined | null, passphrase?: string | undefined | null, note?: string | undefined | null, memberPublicKeyHex?: string | undefined | null): NapiOrgMember

export declare function addWitness(urlStr: string, repoPath: string, label?: string | undefined | null): NapiWitnessResult

export declare function compilePolicy(policyJson: string): string

export declare function completePairing(deviceDid: string, devicePublicKeyHex: string, repoPath: string, capabilitiesJson?: string | undefined | null, passphrase?: string | undefined | null): NapiPairingResult

export declare function createAgentIdentity(agentName: string, capabilities: Array<string>, repoPath: string, passphrase?: string | undefined | null): NapiAgentIdentityBundle

export declare function createIdentity(keyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiIdentityResult

export declare function createOrg(label: string, repoPath: string, passphrase?: string | undefined | null): NapiOrgResult

export declare function createPairingSession(repoPath: string, capabilitiesJson?: string | undefined | null, timeoutSecs?: number | undefined | null, bindAddress?: string | undefined | null, enableMdns?: boolean | undefined | null, passphrase?: string | undefined | null): NapiPairingSession

export declare function delegateAgent(agentName: string, capabilities: Array<string>, parentRepoPath: string, passphrase?: string | undefined | null, expiresInDays?: number | undefined | null, identityDid?: string | undefined | null): NapiDelegatedAgentBundle

export declare function evaluatePolicy(policyJson: string, issuer: string, subject: string, capabilities?: Array<string> | undefined | null, role?: string | undefined | null, revoked?: boolean | undefined | null, expiresAt?: string | undefined | null, repo?: string | undefined | null, environment?: string | undefined | null, signerType?: string | undefined | null, delegatedBy?: string | undefined | null, chainDepth?: number | undefined | null): NapiPolicyDecision

export declare function extendDeviceAuthorization(deviceDid: string, identityKeyAlias: string, days: number, repoPath: string, passphrase?: string | undefined | null): NapiExtensionResult

export declare function generateAuditReport(targetRepoPath: string, authsRepoPath: string, since?: string | undefined | null, until?: string | undefined | null, author?: string | undefined | null, limit?: number | undefined | null): string

export declare function getIdentityPublicKey(identityDid: string, repoPath: string, passphrase?: string | undefined | null): string

export declare function getLatestAttestation(repoPath: string, deviceDid: string): NapiAttestation | null

export declare function getPinnedIdentity(did: string, repoPath: string): NapiPinnedIdentity | null

export declare function joinPairingSession(shortCode: string, endpoint: string, token: string, repoPath: string, deviceName?: string | undefined | null, passphrase?: string | undefined | null): NapiPairingResponse

export declare function linkDeviceToIdentity(identityKeyAlias: string, capabilities: Array<string>, repoPath: string, passphrase?: string | undefined | null, expiresInDays?: number | undefined | null): NapiLinkResult

export declare function listAttestations(repoPath: string): Array<NapiAttestation>

export declare function listAttestationsByDevice(repoPath: string, deviceDid: string): Array<NapiAttestation>

export declare function listOrgMembers(orgDid: string, includeRevoked: boolean, repoPath: string): string

export declare function listPinnedIdentities(repoPath: string): string

export declare function listWitnesses(repoPath: string): string

export interface NapiActionEnvelope {
  envelopeJson: string
  signatureHex: string
  signerDid: string
}

export interface NapiAgentIdentityBundle {
  agentDid: string
  keyAlias: string
  attestationJson: string
  publicKeyHex: string
  repoPath?: string
}

export interface NapiArtifactResult {
  attestationJson: string
  rid: string
  digest: string
  fileSize: number
}

export interface NapiAttestation {
  rid: string
  issuer: string
  subject: string
  deviceDid: string
  capabilities: Array<string>
  signerType?: string
  expiresAt?: string
  revokedAt?: string
  createdAt?: string
  delegatedBy?: string
  json: string
}

export interface NapiChainLink {
  issuer: string
  subject: string
  valid: boolean
  error?: string
}

export interface NapiCommitSignPemResult {
  signaturePem: string
  method: string
  namespace: string
}

export interface NapiCommitSignResult {
  signature: string
  signerDid: string
}

export interface NapiDelegatedAgentBundle {
  agentDid: string
  keyAlias: string
  attestationJson: string
  publicKeyHex: string
  repoPath?: string
}

export interface NapiExtensionResult {
  deviceDid: string
  newExpiresAt: string
  previousExpiresAt?: string
}

export interface NapiIdentityResult {
  did: string
  keyAlias: string
  publicKeyHex: string
}

export interface NapiLinkResult {
  deviceDid: string
  attestationId: string
}

export interface NapiOrgMember {
  memberDid: string
  role: string
  capabilitiesJson: string
  issuerDid: string
  attestationRid: string
  revoked: boolean
  expiresAt?: string
}

export interface NapiOrgResult {
  orgPrefix: string
  orgDid: string
  label: string
  repoPath: string
}

export interface NapiPairingResponse {
  deviceDid: string
  deviceName?: string
  devicePublicKeyHex: string
}

export interface NapiPairingResult {
  deviceDid: string
  deviceName?: string
  attestationRid: string
}

export interface NapiPairingSession {
  sessionId: string
  shortCode: string
  endpoint: string
  token: string
  controllerDid: string
}

export interface NapiPinnedIdentity {
  did: string
  label?: string
  trustLevel: string
  firstSeen: string
  kelSequence?: number
  pinnedAt: string
}

export interface NapiPolicyDecision {
  outcome: string
  reason: string
  message: string
}

export interface NapiRotationResult {
  controllerDid: string
  newKeyFingerprint: string
  previousKeyFingerprint: string
  sequence: number
}

export interface NapiVerificationReport {
  status: NapiVerificationStatus
  chain: Array<NapiChainLink>
  warnings: Array<string>
}

export interface NapiVerificationResult {
  valid: boolean
  error?: string
  errorCode?: string
}

export interface NapiVerificationStatus {
  statusType: string
  at?: string
  step?: number
  missingLink?: string
  required?: number
  verified?: number
}

export interface NapiWitnessResult {
  url: string
  did?: string
  label?: string
}

export declare function pinIdentity(did: string, repoPath: string, label?: string | undefined | null, trustLevel?: string | undefined | null): NapiPinnedIdentity

export declare function removePinnedIdentity(did: string, repoPath: string): void

export declare function removeWitness(urlStr: string, repoPath: string): void

export declare function revokeDeviceFromIdentity(deviceDid: string, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, note?: string | undefined | null): void

export declare function revokeOrgMember(orgDid: string, memberDid: string, repoPath: string, passphrase?: string | undefined | null, note?: string | undefined | null, memberPublicKeyHex?: string | undefined | null): NapiOrgMember

export declare function rotateIdentityKeys(repoPath: string, identityKeyAlias?: string | undefined | null, nextKeyAlias?: string | undefined | null, passphrase?: string | undefined | null): NapiRotationResult

export declare function runDiagnostics(repoPath: string): string

export declare function signActionAsAgent(actionType: string, payloadJson: string, keyAlias: string, agentDid: string, passphrase?: string | undefined | null): NapiActionEnvelope

export declare function signActionAsIdentity(actionType: string, payloadJson: string, identityDid: string, repoPath: string, passphrase?: string | undefined | null): NapiActionEnvelope

export declare function signArtifact(filePath: string, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, expiresInDays?: number | undefined | null, note?: string | undefined | null): NapiArtifactResult

export declare function signArtifactBytes(data: Buffer, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, expiresInDays?: number | undefined | null, note?: string | undefined | null): NapiArtifactResult

export declare function signAsAgent(message: Buffer, keyAlias: string, passphrase?: string | undefined | null): NapiCommitSignResult

export declare function signAsIdentity(message: Buffer, identityDid: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignResult

export declare function signCommit(data: Buffer, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignPemResult

export declare function stopPairingSession(): void

export declare function verifyAttestation(attestationJson: string, issuerPkHex: string): NapiVerificationResult

export declare function verifyAttestationWithCapability(attestationJson: string, issuerPkHex: string, requiredCapability: string): NapiVerificationResult

export declare function verifyAtTime(attestationJson: string, issuerPkHex: string, atRfc3339: string): NapiVerificationResult

export declare function verifyAtTimeWithCapability(attestationJson: string, issuerPkHex: string, atRfc3339: string, requiredCapability: string): NapiVerificationResult

export declare function verifyChain(attestationsJson: Array<string>, rootPkHex: string): NapiVerificationReport

export declare function verifyChainWithCapability(attestationsJson: Array<string>, rootPkHex: string, requiredCapability: string): NapiVerificationReport

export declare function verifyChainWithWitnesses(attestationsJson: Array<string>, rootPkHex: string, receiptsJson: Array<string>, witnessKeysJson: Array<string>, threshold: number): NapiVerificationReport

export declare function verifyDeviceAuthorization(identityDid: string, deviceDid: string, attestationsJson: Array<string>, identityPkHex: string): NapiVerificationReport

export declare function version(): string

export declare function waitForPairingResponse(timeoutSecs?: number | undefined | null): NapiPairingResponse
