/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NapiPairingHandle {
  static createSession(repoPath: string, capabilitiesJson?: string | undefined | null, timeoutSecs?: number | undefined | null, bindAddress?: string | undefined | null, enableMdns?: boolean | undefined | null, passphrase?: string | undefined | null): Promise<NapiPairingHandle>
  get session(): NapiPairingSession
  waitForResponse(timeoutSecs?: number | undefined | null): Promise<NapiPairingResponse>
  stop(): Promise<void>
}

export declare function addOrgMember(orgDid: string, memberLabel: string, role: string, repoPath: string, capabilitiesJson?: string | undefined | null, passphrase?: string | undefined | null, expiresAt?: number | undefined | null): NapiOrgMember

export declare function addWitness(urlStr: string, aid: string, repoPath: string, label?: string | undefined | null): NapiWitnessResult

export declare function compilePolicy(policyJson: string): string

export declare function createAgentIdentity(agentName: string, capabilities: Array<string>, repoPath: string, passphrase?: string | undefined | null): NapiAgentIdentityBundle

export declare function createIdentity(keyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiIdentityResult

export declare function createOrg(label: string, repoPath: string, passphrase?: string | undefined | null): NapiOrgResult

/** A typed credential verdict report (the F.5 outcome). */
export interface CredentialReport {
  /** The discriminated status. */
  status: CredentialStatus
  /** Issuer AID (`did:keri:`) — present on `Valid`. */
  issuer?: string
  /** Subject (holder) AID — present on `Valid`. */
  subject?: string
  /** Granted capabilities — present on `Valid`. Never silently dropped (fn-153.2). */
  caps?: Array<string>
  /** The KEL position the verdict is as-of — present on `Valid`. */
  asOf?: number
  /** The KEL position a revocation was anchored at — present on `CredentialRevoked`. */
  revokedAt?: number
  /** The expiry instant — present on `Expired`. */
  expiredAt?: string
  /** Failure detail — present on `MalformedRequest`. */
  message?: string
  /** The offending request field — present on `InputTooLarge`. */
  field?: string
}

/** The outcome of [`verify_credential`] — mirrors the Rust `CredentialVerdict` wire kinds. */
export declare const enum CredentialStatus {
  /** Authentic, anchored, witnessed per policy, unexpired, and not revoked. */
  Valid = 'Valid',
  /** Recomputed ACDC SAID did not match the embedded one. */
  SaidMismatch = 'SaidMismatch',
  /** Attributes failed schema validation, or the schema SAID is not the pinned one. */
  SchemaInvalid = 'SchemaInvalid',
  /** The issuance was unanchored or the issuer signature did not verify. */
  IssuerSignatureInvalid = 'IssuerSignatureInvalid',
  /** The registry (`vcp`) was never anchored in the issuer KEL. */
  RegistryNotEstablished = 'RegistryNotEstablished',
  /** A qualifying revocation is anchored at/before the presentation; see `revokedAt`. */
  CredentialRevoked = 'CredentialRevoked',
  /** The credential expired; see `expiredAt`. */
  Expired = 'Expired',
  /** A lifecycle anchor missed witness quorum under `RequireWitnesses`. */
  WitnessQuorumNotMet = 'WitnessQuorumNotMet',
  /** The issuer KEL forks (fail-closed in both witness policies). */
  IssuerKelDuplicitous = 'IssuerKelDuplicitous',
  /** The request JSON could not be parsed; see `message`. */
  MalformedRequest = 'MalformedRequest',
  /** A supplied KEL failed signature authentication (forged or missing attachments). */
  KelUnauthenticated = 'KelUnauthenticated',
  /** A request slice exceeded its bound; see `field`. */
  InputTooLarge = 'InputTooLarge',
  /** The request schema version is not understood by this build. */
  UnsupportedSchemaVersion = 'UnsupportedSchemaVersion',
  /** Unrecognized verdict kind (forward-compat guard). */
  Unknown = 'Unknown'
}

export declare function delegateAgent(agentName: string, capabilities: Array<string>, parentRepoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null, identityDid?: string | undefined | null, curve?: string | undefined | null): NapiDelegatedAgentBundle

export declare function evaluatePolicy(policyJson: string, issuer: string, subject: string, capabilities?: Array<string> | undefined | null, role?: string | undefined | null, revoked?: boolean | undefined | null, expiresAt?: string | undefined | null, repo?: string | undefined | null, environment?: string | undefined | null, signerType?: string | undefined | null, delegatedBy?: string | undefined | null, chainDepth?: number | undefined | null): NapiPolicyDecision

export declare function extendDeviceAuthorization(deviceDid: string, identityKeyAlias: string, expiresIn: number, repoPath: string, passphrase?: string | undefined | null): NapiExtensionResult

export declare function generateAuditReport(targetRepoPath: string, authsRepoPath: string, since?: string | undefined | null, until?: string | undefined | null, author?: string | undefined | null, limit?: number | undefined | null): string

/**
 * Generate an in-memory Ed25519 keypair without keychain, Git, or filesystem access.
 *
 * Args:
 * (no arguments)
 *
 * Usage:
 * ```ignore
 * let kp = generate_inmemory_keypair()?;
 * // kp.private_key_hex, kp.public_key_hex, kp.did
 * ```
 */
export declare function generateInmemoryKeypair(curve?: string | undefined | null): NapiInMemoryKeypair

export declare function getIdentityPublicKey(identityDid: string, repoPath: string, passphrase?: string | undefined | null): string

export declare function getLatestAttestation(repoPath: string, deviceDid: string): NapiAttestation | null

export declare function getPinnedIdentity(did: string, repoPath: string): NapiPinnedIdentity | null

export declare function joinPairingSession(shortCode: string, endpoint: string, token: string, repoPath: string, deviceName?: string | undefined | null, passphrase?: string | undefined | null): Promise<NapiPairingResponse>

export declare function linkDeviceToIdentity(identityKeyAlias: string, capabilities: Array<string>, repoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null): NapiLinkResult

export declare function listAttestations(repoPath: string): Array<NapiAttestation>

export declare function listAttestationsByDevice(repoPath: string, deviceDid: string): Array<NapiAttestation>

export declare function listOrgMembers(orgDid: string, includeRevoked: boolean, repoPath: string, passphrase?: string | undefined | null): string

export declare function listPinnedIdentities(repoPath: string): string

export declare function listWitnesses(repoPath: string): string

export interface NapiActionEnvelope {
  envelopeJson: string
  signatureHex: string
  signerDid: string
}

export interface NapiAgentIdentityBundle {
  agentDid: string
  keyAlias: string
  attestationJson: string
  publicKeyHex: string
  repoPath?: string
}

export interface NapiArtifactResult {
  attestationJson: string
  rid: string
  digest: string
  fileSize: number
}

export interface NapiAttestation {
  rid: string
  issuer: string
  subject: string
  deviceDid: string
  signerType?: string
  expiresAt?: string
  revokedAt?: string
  createdAt?: string
  delegatedBy?: string
  json: string
}

export interface NapiChainLink {
  issuer: string
  subject: string
  valid: boolean
  error?: string
}

export interface NapiCommitSignPemResult {
  signaturePem: string
  method: string
  namespace: string
}

export interface NapiCommitSignResult {
  signature: string
  signerDid: string
}

export interface NapiDelegatedAgentBundle {
  agentDid: string
  keyAlias: string
  attestationJson: string
  publicKeyHex: string
  repoPath?: string
}

export interface NapiExtensionResult {
  deviceDid: string
  newExpiresAt: string
  previousExpiresAt?: string
}

export interface NapiIdentityResult {
  did: string
  keyAlias: string
  publicKeyHex: string
}

export interface NapiInMemoryKeypair {
  privateKeyHex: string
  publicKeyHex: string
  did: string
}

export interface NapiLinkResult {
  deviceDid: string
  attestationId: string
}

export interface NapiOrgMember {
  memberDid: string
  role: string
  capabilitiesJson: string
  issuerDid: string
  attestationRid: string
  revoked: boolean
  expiresAt?: string
}

export interface NapiOrgResult {
  orgPrefix: string
  orgDid: string
  label: string
  repoPath: string
}

export interface NapiPairingResponse {
  deviceDid: string
  deviceName?: string
  devicePublicKeyHex: string
}

export interface NapiPairingSession {
  sessionId: string
  shortCode: string
  endpoint: string
  token: string
  controllerDid: string
}

export interface NapiPinnedIdentity {
  did: string
  label?: string
  trustLevel: string
  firstSeen: string
  kelSequence?: number
  pinnedAt: string
}

export interface NapiPolicyDecision {
  outcome: string
  reason: string
  message: string
}

export interface NapiRotationResult {
  controllerDid: string
  newKeyFingerprint: string
  previousKeyFingerprint: string
  sequence: number
}

export interface NapiVerificationReport {
  status: NapiVerificationStatus
  chain: Array<NapiChainLink>
  warnings: Array<string>
}

export interface NapiVerificationResult {
  valid: boolean
  error?: string
  errorCode?: string
}

export interface NapiVerificationStatus {
  statusType: string
  at?: string
  step?: number
  missingLink?: string
  required?: number
  verified?: number
}

export interface NapiWitnessResult {
  url: string
  did?: string
  label?: string
}

export declare function pinIdentity(did: string, repoPath: string, label?: string | undefined | null, trustLevel?: string | undefined | null): NapiPinnedIdentity

/** A typed presentation verdict report (holder-binding outcome). */
export interface PresentationReport {
  /** The discriminated status. */
  status: PresentationStatus
  /** Issuer AID (`did:keri:`) — present on `Valid`. */
  issuer?: string
  /** Subject (holder) AID whose current key signed — present on `Valid`. */
  subject?: string
  /** The subject's proven root (its delegator when delegated, itself otherwise) — present on `Valid`. */
  subjectRoot?: string
  /** Granted capabilities — present on `Valid`. Never silently dropped (fn-153.2). */
  caps?: Array<string>
  /** Optional informational role claim — present on `Valid`. */
  role?: string
  /** Optional credential expiry — present on `Valid`. */
  expiresAt?: string
  /** The nested credential verdict — present on `CredentialNotValid`. */
  credential?: CredentialReport
  /** Failure detail — present on `MalformedRequest`. */
  message?: string
  /** The offending request field — present on `InputTooLarge`. */
  field?: string
}

/** The outcome of [`verify_presentation`] — mirrors the Rust `PresentationVerdict` wire kinds. */
export declare const enum PresentationStatus {
  /** Holder-binding proven: the credential is valid and the presentation is current-key signed. */
  Valid = 'Valid',
  /** The presentation signature is not the subject AID's current key. */
  HolderNotCurrentKey = 'HolderNotCurrentKey',
  /** Bound to a different audience than expected. */
  WrongAudience = 'WrongAudience',
  /** Challenge mismatched or already consumed (single-use replay protection). */
  NonceMismatchOrConsumed = 'NonceMismatchOrConsumed',
  /** Non-interactive TTL presentation expired. */
  Expired = 'Expired',
  /** The subject KEL could not be replayed. */
  SubjectKelInvalid = 'SubjectKelInvalid',
  /** The credential itself is not valid; see `credential` for the nested verdict. */
  CredentialNotValid = 'CredentialNotValid',
  /** The request JSON could not be parsed; see `message`. */
  MalformedRequest = 'MalformedRequest',
  /** A supplied KEL failed signature authentication (forged or missing attachments). */
  KelUnauthenticated = 'KelUnauthenticated',
  /** A request slice exceeded its bound; see `field`. */
  InputTooLarge = 'InputTooLarge',
  /** The request schema version is not understood by this build. */
  UnsupportedSchemaVersion = 'UnsupportedSchemaVersion',
  /** Unrecognized verdict kind (forward-compat guard). */
  Unknown = 'Unknown'
}

export declare function removePinnedIdentity(did: string, repoPath: string): void

export declare function removeWitness(urlStr: string, repoPath: string): void

export declare function revokeDeviceFromIdentity(deviceDid: string, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, note?: string | undefined | null): void

export declare function revokeOrgMember(orgDid: string, memberDid: string, repoPath: string, passphrase?: string | undefined | null): NapiOrgMember

export declare function rotateIdentityKeys(repoPath: string, identityKeyAlias?: string | undefined | null, nextKeyAlias?: string | undefined | null, passphrase?: string | undefined | null): NapiRotationResult

export declare function runDiagnostics(repoPath: string, passphrase?: string | undefined | null): string

export declare function signActionAsAgent(actionType: string, payloadJson: string, keyAlias: string, agentDid: string, repoPath: string, passphrase?: string | undefined | null): NapiActionEnvelope

export declare function signActionAsIdentity(actionType: string, payloadJson: string, identityDid: string, repoPath: string, passphrase?: string | undefined | null): NapiActionEnvelope

/**
 * Sign an action envelope with a hex-encoded signing seed.
 *
 * Curve is dispatched via the `curve` argument (defaults to P-256 per the
 * workspace wire-format curve-tagging rule).
 *
 * Args:
 * * `private_key_hex`: 32-byte signing seed as hex string (64 chars).
 * * `action_type`: Application-defined action type (e.g. "tool_call").
 * * `payload_json`: JSON string for the payload field.
 * * `identity_did`: Signer's identity DID (e.g. "did:keri:E...").
 * * `curve`: Optional curve hint (`"Ed25519"` / `"P256"`). Absent → P-256.
 *
 * Usage:
 * ```ignore
 * let envelope = sign_action_raw("deadbeef...".into(), "tool_call".into(), "{}".into(), "did:keri:E...".into(), Some("P256".into()))?;
 * ```
 */
export declare function signActionRaw(privateKeyHex: string, actionType: string, payloadJson: string, identityDid: string, curve?: string | undefined | null): string

export declare function signArtifact(filePath: string, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null, note?: string | undefined | null, commitSha?: string | undefined | null): NapiArtifactResult

export declare function signArtifactBytes(data: Buffer, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null, expiresIn?: number | undefined | null, note?: string | undefined | null, commitSha?: string | undefined | null): NapiArtifactResult

/**
 * Sign raw bytes with a raw Ed25519 private key, producing a dual-signed attestation.
 *
 * No keychain or filesystem access required.
 *
 * Args:
 * * `data`: The raw bytes to sign.
 * * `private_key_hex`: Ed25519 seed as hex string (64 chars = 32 bytes).
 * * `identity_did`: Identity DID string (must be `did:keri:` format).
 * * `expires_in`: Optional duration in seconds until expiration.
 * * `note`: Optional human-readable note.
 *
 * Usage:
 * ```ignore
 * let result = sign_artifact_bytes_raw(buffer, "abcd...".into(), "did:keri:E...".into(), None, None)?;
 * ```
 */
export declare function signArtifactBytesRaw(data: Buffer, privateKeyHex: string, identityDid: string, expiresIn?: number | undefined | null, note?: string | undefined | null, commitSha?: string | undefined | null): NapiArtifactResult

export declare function signAsAgent(message: Buffer, keyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignResult

export declare function signAsIdentity(message: Buffer, identityDid: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignResult

/**
 * Sign raw bytes with a hex-encoded signing seed.
 *
 * Curve is dispatched via the `curve` argument (defaults to P-256 per the
 * workspace wire-format curve-tagging rule).
 *
 * Args:
 * * `private_key_hex`: 32-byte signing seed as hex string (64 chars).
 * * `message`: The bytes to sign.
 * * `curve`: Optional curve hint (`"Ed25519"` / `"P256"`). Absent → P-256.
 *
 * Usage:
 * ```ignore
 * let sig = sign_bytes_raw("deadbeef...".into(), buffer, Some("P256".into()))?;
 * ```
 */
export declare function signBytesRaw(privateKeyHex: string, message: Buffer, curve?: string | undefined | null): string

export declare function signCommit(data: Buffer, identityKeyAlias: string, repoPath: string, passphrase?: string | undefined | null): NapiCommitSignPemResult

/**
 * Verify an action envelope's signature with a raw public key.
 * Curve dispatched via the `curve` argument; supports Ed25519 and P-256.
 *
 * Args:
 * * `envelope_json`: The complete action envelope as a JSON string.
 * * `public_key_hex`: The signer's public key in hex format
 *   (64 chars for Ed25519, 66 or 130 chars for P-256).
 * * `curve`: Optional curve hint (`"Ed25519"` / `"P256"`). Absent → P-256
 *   default per the workspace wire-format curve-tagging rule.
 *
 * Usage:
 * ```ignore
 * let result = verify_action_envelope("{...}".into(), "abcd1234...".into(), Some("P256".into()))?;
 * ```
 */
export declare function verifyActionEnvelope(envelopeJson: string, publicKeyHex: string, curve?: string | undefined | null): NapiVerificationResult

export declare function verifyAttestation(attestationJson: string, issuerPkHex: string): Promise<NapiVerificationResult>

export declare function verifyAtTime(attestationJson: string, issuerPkHex: string, atRfc3339: string): Promise<NapiVerificationResult>

export declare function verifyChain(attestationsJson: Array<string>, rootPkHex: string): Promise<NapiVerificationReport>

export declare function verifyChainWithWitnesses(attestationsJson: Array<string>, rootPkHex: string, receiptsJson: Array<string>, witnessKeysJson: Array<string>, threshold: number): Promise<NapiVerificationReport>

/**
 * Verify an issued **credential** from a bundled JSON request, returning a typed report.
 *
 * Args:
 * * `request_json`: A `VerifyCredentialRequest` JSON document.
 *
 * Usage (TypeScript):
 * ```ignore
 * import { verifyCredential, CredentialStatus } from "@auths-dev/sdk";
 * const report = verifyCredential(bundleJson);
 * if (report.status === CredentialStatus.CredentialRevoked) { /* report.revokedAt *\/ }
 * ```
 */
export declare function verifyCredential(requestJson: string): CredentialReport

export declare function verifyDeviceAuthorization(identityDid: string, deviceDid: string, attestationsJson: Array<string>, identityPkHex: string): Promise<NapiVerificationReport>

/**
 * Verify a credential **presentation** from a bundled JSON request, returning a typed report.
 *
 * The request is the fn-153.3 `VerifyPresentationRequest` bundle (keys CESR-tagged inside).
 * Denials and malformed input are returned as a `status`, not thrown.
 *
 * Args:
 * * `request_json`: A `VerifyPresentationRequest` JSON document.
 *
 * Usage (TypeScript):
 * ```ignore
 * import { verifyPresentation, PresentationStatus } from "@auths-dev/sdk";
 * const report = verifyPresentation(bundleJson);
 * if (report.status === PresentationStatus.Valid) { /* report.subject, report.caps *\/ }
 * ```
 */
export declare function verifyPresentation(requestJson: string): PresentationReport

export declare function version(): string
